### ISSUE TITLE
Add support for High-Performance Order Storage (HPOS)

### ISSUE THREAD

**Issue by loueranta-paytrail** [paytrail/paytrail-for-woocommerce#118]
WooCommerce is migrating from post and metadata based tables to dedicated tables for orders:
https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book

So, let's add support for HPOS.

**Comment by thannus** [comment]
https://github.com/paytrail/paytrail-for-woocommerce/blob/36142643d808936c68324a21511475e73aa7df29/src/Gateway.php#L1861

The variable $total_with_tax should be calculated with rounding, ie. the third parameter for $order->get_line_total should be true. The total amount is in any case rounded, because the customer never pays in fractional cents. With this change the amounts in the test case become:

$total_without_tax = 0.645161
$total_with_tax = 0.80

$tax_total = 0.80 - 0.645161 = 0.154839

$tax_rate = round( ( 0.154839 / 0.645161) * 100) = 24

**Comment by chrisgan** [comment]
As part of undertaking this work I have found a bug in WooCommerce that affects the compatibility with HPOS and our module, with regards to refunds.
This has been confirmed as bug by the WooCommerce team here https://github.com/woocommerce/woocommerce/issues/44153

**Comment by chrisgan** [comment]
We are code complete on the changes and I have tested with the latest nightly build of WooCommerce now that their issue has been resolved. We should wait until Woo Commerce release this fix, and then we can test against that version to confirm compatibility. Until then we will not merge the changes in for this work.

**Comment by loueranta-paytrail** [comment]
This was added in #138
