### ISSUE TITLE
Incorrect line item VAT percentage

### ISSUE THREAD

**Issue by loueranta-paytrail** [paytrail/paytrail-for-woocommerce#122]
Full description here: https://wordpress.org/support/topic/incorrect-line-item-vat-percentage/

**Comment by thannus** [comment]
https://github.com/paytrail/paytrail-for-woocommerce/blob/36142643d808936c68324a21511475e73aa7df29/src/Gateway.php#L1861


$total_with_tax     = $order->get_line_total($item, true, false); 

The variable $total_with_tax should be calculated with rounding, ie. the third parameter for $order->get_line_total should be true. The total amount is in any case rounded, because the customer never pays in fractional cents. With this change the amounts in the test case become:

$total_without_tax = 0.645161
$total_with_tax = 0.80

$tax_total = 0.80 - 0.645161 = 0.154839

$tax_rate = round( ( 0.154839 / 0.645161) * 100) = 24

**Comment by loueranta-paytrail** [comment]
This was fixed on #124 and released on 1.3.11 version
